server {
    listen 80;

    location /incidents {
        proxy_pass http://backend:8080;
    }

    location /tags {
        proxy_pass http://backend:8080;
    }

    location /users {
        proxy_pass http://backend:8080;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
